#!/usr/bin/env bash
#
# Git commit wrapper.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" maintenance $* || exit 1

# Fix positional arguments
shift

# Run git command
keyringer_exec git "$BASEDIR" commit $*
