#!/usr/bin/env bash
#
# Decrypt files.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" read $* || exit 1

# Get file
keyringer_get_file "$2"

# Decrypt
cat "$KEYDIR/$FILE" | $GPG --use-agent -d -

# Exit
exit "$?"
