#!/usr/bin/env bash
#
# Decrypt secret header to clipboard, sleep and cleanup.
#

# Load functions
LIB="`dirname $0`/../functions"
source "$LIB" || exit 1

# Clip password
shift
keyringer $KEYRING xclip $*

# Se window switch combo
if [ -z "$XDOTOOL_NEXT_WINDOW" ]; then
  XDOTOOL_NEXT_WINDOW="alt+Tab"
fi

# Move to the next window
if which xdotool &> /dev/null; then
  xdotool key $XDOTOOL_NEXT_WINDOW
fi

# Sleep
sleep 5

# Overwrite clipboard
echo $RANDOM | sha256sum | base64 -d | xclip
